// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpKDIzIWKFxb8MsN6ZsJZ0DrZwAJzYa2I',
    appId: '1:468054081430:web:9cd860420bef076f19a7b7',
    messagingSenderId: '468054081430',
    projectId: 'flash-card-92b53',
    authDomain: 'flash-card-92b53.firebaseapp.com',
    storageBucket: 'flash-card-92b53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZowSLAP81M3V7EhrG4ln4QEM2VsUgw9o',
    appId: '1:468054081430:android:44bdc052d379193719a7b7',
    messagingSenderId: '468054081430',
    projectId: 'flash-card-92b53',
    storageBucket: 'flash-card-92b53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3S6dK759T9N8WFXacyYuRWteKPBs6ez8',
    appId: '1:468054081430:ios:06985a71addaf19a19a7b7',
    messagingSenderId: '468054081430',
    projectId: 'flash-card-92b53',
    storageBucket: 'flash-card-92b53.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3S6dK759T9N8WFXacyYuRWteKPBs6ez8',
    appId: '1:468054081430:ios:c424fe1ed9464eb519a7b7',
    messagingSenderId: '468054081430',
    projectId: 'flash-card-92b53',
    storageBucket: 'flash-card-92b53.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
